apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true" # (2)
# Deployment specifications
spec:
  # Replicas (required)
  replicas: 1 # (3)
  # Bootstrap servers (required)
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092 # (4)
  # Kafka Connect configuration (recommended)
  # config: # (5)
  #   group.id: my-connect-cluster
  #   offset.storage.topic: my-connect-cluster-offsets
  #   config.storage.topic: my-connect-cluster-configs
  #   status.storage.topic: my-connect-cluster-status
  #   key.converter: io.apicurio.registry.utils.converter.AvroConverter
  #   key.converter.apicurio.registry.url: http://apicurio-apicurio-registry.kafka-manager/apis/registry/v2
  #   key.converter.apicurio.registry.auto-register: true
  #   key.converter.apicurio.registry.find-latest: true
  #   value.converter: io.apicurio.registry.utils.converter.AvroConverter
  #   value.converter.apicurio.registry.url: http://apicurio-apicurio-registry.kafka-manager/apis/registry/v2
  #   value.converter.apicurio.registry.auto-register: true
  #   value.converter.apicurio.registry.find-latest: true
  #   schema.name.adjustment.mode: avro
  # Resources requests and limits (recommended)
  resources: # (6)
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 2Gi
  build:
    output: 
      type: docker
      image: hellices/kafka-connect:1.4
      pushSecret: docker-hub-secret
    plugins: 
      - name: debezium-connector-postgres
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.7.3.Final/debezium-connector-postgres-2.7.3.Final-plugin.tar.gz
      - name: apicurio-converter
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/apicurio/apicurio-registry-distro-connect-converter/2.0.2.Final/apicurio-registry-distro-connect-converter-2.0.2.Final.tar.gz

            