{{- if (.Values.config).yaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odd-platform.fullname" . }}-application-conf
  labels:
    {{- include "odd-platform.labels" . | nindent 4 }}
data:
  application.yml: |-
    {{- toYaml .Values.config.yaml | nindent 4}}
{{ end }}